### ISSUE TITLE
Ability to blur images

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [chengdazhi/StyleImageView#1]

**Comment by chengdazhi** [comment]
@mori-honest Because this library is based on ColorMatrixColorFilter which is very fast, and I haven't found a matrix to support blur, I cannot add this function until I find one.

Although, please note that the Styler class can work on any subclass of ImageView. So if you want to use a custom ImageView that supports blurring, you can add color filter to it via Styler Object. You can check the wiki for details.
